
comment: "This issue is closed because it does not meet our issue template. Please read it."
issueConfigs:
- content:
# Template: bug report
  - "Describe the bug"
  - "To Reproduce"
  - "Desktop (please complete the following information):"
  - "Additional context"
- content:
# Template: feature request
  - "Is your feature request related to a problem? Please describe."
  - "Describe the solution you'd like"
  - "Describe alternatives you've considered"
  - Additional context
caseInsensitive: true
label: "closed by bot"

